### ISSUE TITLE
libai 文档的主题是否需要和 oneflow 仓库的统一？

### ISSUE THREAD

**Issue by doombeaker** [Oneflow-Inc/libai#115]
目前 libai 仓库的风格都用的默认 sphinx 主题，和 oneflow 仓库的不搭。oneflow docs/flowvision 仓库的主题是之前晟航 @jackalcooper 筛选的 furo 主题，比较好看。我个人建议libai也应该用 furo 比较好吧。或者退而求其次，起码所有对外 API 文档主题风格要统一。

![image](https://user-images.githubusercontent.com/3351623/154019340-f971a226-2d68-477a-ae61-fa26477be435.png)

![image](https://user-images.githubusercontent.com/3351623/154019530-ffdad7be-a0e3-42ac-a697-5c26c0407ccf.png)

@rentainhe @lixiang007666 

如果要统一的话，参考 oneflow 仓库，sphinx 配置改两个地方就可以了，分别是：

https://github.com/Oneflow-Inc/oneflow/blob/master/docs/source/conf.py#L82
https://github.com/Oneflow-Inc/oneflow/blob/master/docs/requirements.txt#L3

**Comment by rentainhe** [comment]
已经统一了~迟哥这个issue我就先close咯~
