### ISSUE TITLE
LiBai Docs问题汇总

### ISSUE THREAD

**Issue by rentainhe** [Oneflow-Inc/libai#149]
## Contents
这个issue主要记录LiBai文档中的问题，以及解决方案（如果有），目前相关联的PR如下:
- issue下的任务安排: https://github.com/Oneflow-Inc/OneTeam/issues/917#issuecomment-1054006331
- optim, trainer, model, cv dataset相关文档PR: https://github.com/Oneflow-Inc/libai/pull/148

## 待讨论和解决的问题
- [x] 文档中没有展示出类的`__init__`方法
- [x] GraphTrainer目前没有Docstring，需要补全
- [x] 感觉`libai.trainer.trainer`这个module命名有点奇怪

## 已解决的问题
- 加载文档的时候类方法的排序是按照首字母排序, 没有按照原本类中的方法顺序排序，解决方案, 添加`member-order: bysource`如下:
```python
libai.trainer.default module
---------------------------------
.. currentmodule:: libai.trainer
.. automodule:: libai.trainer
    :member-order: bysource
    :members: 
        default_setup,
        DefaultTrainer,
```

**Comment by Ldpe2G** [comment]
我看 torch 的文档，也没看到 `__init__` 方法
