### ISSUE TITLE
添加docstring中的libai projects开发tutorial

### ISSUE THREAD

**Issue by xiezipeng-ML** [Oneflow-Inc/libai#159]
### 需求

如果开发者想进行新任务的开发(比如论文复现，finetune task的添加)，那么基于`libai`的库，怎么实现最少的代码开发工作？

首先我们必须明确的是基于`libai`去进行新任务的开发, 有什么样的好处：

1. 对于用户来说：`libai`的很多特性在projects里面都可以继承，不用自己重新造轮子，比如：
    - 用户可以继承`libai`的`trainer`和`lazyconfig`，只需要自己重构`model`和`dataloader`，可以实现代码最小化。
    - 用户可以享受到`libai`的特性：`libai`会保存配置文件，可以很快地复现自己跑过的实验；`libai`在训练期间输出多样化的训练信息，比如剩余训练时间，当前iter进度，吞吐量，loss信息，当前learning rate等。
    - 可以通过简单的设置分布式训练参数进行分布式训练。

### 新建任务

我们以新建一个bert_finetune的task为例，整体代码可见[projects_QQP](https://github.com/Oneflow-Inc/libai/tree/main/projects/QQP)。

首先我们来看整体的结构，对于一个新建的任务来说，我们主要的工作其实在于：
- 编写`config.py`，这个config是该任务独立的config，其中包含了任务相关的类的定义，以及该任务用到的参数。以下是一些关于config文件的注意事项（以[QQP-config.py](https://github.com/Oneflow-Inc/libai/blob/main/projects/QQP/configs/config_qqp.py)为例）：
    1. 这里面以LazyCall（LazyCall不会真正调用定义的对象，而是返回一个用于描述调用的dict）的形式定义了tokenizer、dataloader、model。
    2. 可以看到该文件导入了很多东西，从configs.common中导入的一般是libai已经写好的一些模型参数和配套的对象，方便我们直接使用或者修改部分后使用。
    3. 还可以看到该文件中有`build_nlp_train_loader`这个方法，这是nlp任务中可以直接帮我们构建好一个dataloader，而不用写过多的例如`sampler`、`collate_fn`之类的东西。

- 编写`model.py`, 与新建任务的模型相关，libai中的model的构建方式与平常oneflow中的大致相同。这部分有些注意事项如下（以[QQP-model.py](https://github.com/Oneflow-Inc/libai/blob/main/projects/QQP/modeling/model.py)为例）：
    1. 由于使用libai默认的训练方式会用到Graph静态图的训练，所以loss的计算需要放在模型内部完成。
    2. 模型的`forward`返回值需要是字典的形式，可以看libai中[trainer.py](https://github.com/Oneflow-Inc/libai/blob/main/libai/trainer/trainer.py#L275)，以及[grapg_base.py](https://github.com/Oneflow-Inc/libai/blob/main/libai/models/utils/graph_base.py#L83)就可以看到loss的backward方式。
    3. 模型内部定义`tensor`时需要`to_global`，将local的`tensor`转为一致性视角下的`tensor`。
    4. 定义相关`layers`或者是`activation`可直接调用`libai.layers`中写好的，因为这些layers已经定义好了sbp的划分方式。

- 编写`dataset.py`, 与新建模型的数据集相关，这部分的相关注意事项有（以[QQP_dataset.py](https://github.com/Oneflow-Inc/libai/tree/main/projects/QQP/dataset)为例）：
    1. dataset对象的构建方法基本与平时使用oneflow一致。
    2. 不同的地方在于我们需要用到[`DistTensorData`](https://github.com/Oneflow-Inc/libai/blob/main/libai/data/structures.py#L26)和[`Instance`](https://github.com/Oneflow-Inc/libai/blob/main/libai/data/structures.py#L93)这两个方法，其中`DistTensorData`主要是将`Dataset`中的`__getitem__`的返回数据进行`to_gloabl`，`Instance`将需要返回的数据打包成一个元数据的形式，就像[demo.py](https://github.com/Oneflow-Inc/libai/blob/main/projects/QQP/dataset/data_utils.py#L41)中的做法一样。
    3. Dataset中的每个batch形状必须一致，因为需要构建静态图训练。
    4. Dataset中__getitem__方法返回的key必须与model中forward函数参数名一致。

```
libai
    configs/
        ...
    libai/
        ...
    tests/
        ...
    tools/
        ...
    projects/
        your_task/
            configs/
              config.py
            dataset/
              dataset.py
            modeling/
              model.py
```

#### 函数入口

[tools.train_net.py](https://github.com/Oneflow-Inc/libai/blob/main/tools/train_net.py)是libai中提供的默认的主要函数入口，所以我们基于该文件只需要改写部分函数即可使用。

当projects较为复杂时，可能需要重新定义一些指标的计算，`train_net.py`样例:

```python
import os
import sys

import numpy as np
from scipy.stats import spearmanr

from libai.config import LazyConfig, default_argument_parser, try_get_key
from libai.evaluation import DatasetEvaluator
from libai.trainer import DefaultTrainer, default_setup
from libai.utils import distributed as dist
from libai.utils.checkpoint import Checkpointer

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir)))


def spearman_target(cos_sim, labels):
    # 计算spearman指标
    return spearmanr(cos_sim, labels).correlation


class MyEvaluator(DatasetEvaluator):
    # 重写默认的evaluator
    def __init__(self, cfg):
        self.cfg = cfg
        self._predictions = []

    def reset(self):
        self._predictions = []

    def process(self, inputs, outputs):
        # inputs是model每个batch接收的数据，outputs是model每个batch输出的内容（这里是eval环节）
        cos_sim = outputs["cos_sim"]
        labels = outputs["labels"]
        # 每个batch的结果添加到self._predictions
        self._predictions.append({"cos_sim": cos_sim, "labels": labels})

    def evaluate(self):
        if not dist.is_main_process():
            return {}
        else:
            predictions = self._predictions
        sim_array = np.array([])
        label_array = np.array([])
        for prediction in predictions:
            sim_array = np.append(sim_array, dist.tton(prediction["cos_sim"]))
            label_array = np.append(label_array, dist.tton(prediction["labels"]))
        self._results = spearman_target(sim_array, label_array)
        return {"spearman": self._results}


class Trainer(DefaultTrainer):
    # 重写evaluator后需要在trainer中重载该函数
    @classmethod
    def build_evaluator(cls, cfg):
        return MyEvaluator(cfg)


def main(args):
    cfg = LazyConfig.load(args.config_file)
    cfg = LazyConfig.apply_overrides(cfg, args.opts)
    default_setup(cfg, args)

    if args.fast_dev_run:
        cfg.train.train_epoch = 0
        cfg.train.train_iter = 20
        cfg.train.eval_period = 10
        cfg.train.log_period = 1

    if args.eval_only:
        tokenizer = None
        if try_get_key(cfg, "tokenization.setup", default=False):
            tokenizer = Trainer.build_tokenizer(cfg)
        model = Trainer.build_model(cfg)
        Checkpointer(model, save_dir=cfg.train.output_dir).resume_or_load(
            cfg.train.load_weight, resume=args.resume
        )
        graph = Trainer.build_graph(cfg, model, is_train=False)
        test_loader = Trainer.build_test_loader(cfg, tokenizer)
        res = Trainer.test(cfg, test_loader, graph)  # noqa
        return

    trainer = Trainer(cfg)
    return trainer.train()


if __name__ == "__main__":
    args = default_argument_parser().parse_args()
    main(args)
```

#### 重定义model

接下来我们定义`model.py`，这里不需要重新定义Graph模型，因为在trainer中会自动根据model创建Graph，以下是一个示例：

```python
from oneflow import nn

class MyModel(nn.Module):
    def __init__(self, cfg):
        ```
        这里的cfg里面的参数 对应config.py中的my_cfg
        ```
        ...

    def forward(self, tokens, padding_mask, types, label):
        ...
        return {‘loss’: loss}

```

#### 重新定义datasets

定义自己的dataset.py十分简单，下面是一个dataset示例：

```python
class TrainDataset(Dataset):
    def __init__(self, data):
        self.data = data
        self.tokenizer = tokenizer
        self.pad_id = self.tokenizer.pad_token_id
        self.cls_id = self.tokenizer.cls_token_id
        self.sep_id = self.tokenizer.sep_token_id

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        ...
        return Instance(
        input_ids=DistTensorData(flow.tensor(data["input_ids"], dtype=flow.long)),
        attention_mask=DistTensorData(flow.tensor(data["attention_mask"], dtype=flow.long)),
        )
```

#### 重新定义config

`libai`的`config`比较特殊, 采用`lazyconfig`的形式, 可以是`.py`文件, 在保存时会保存为`.yaml`。
在这里先简单的讲讲完整的`config.py`, 以及怎么继承`config.py`。

首先, 在训练的任务里面, `config.py`有几个必要的字段:
- `train`: 和训练相关的入参，字典形式。
- `model`: 和模型结构相关, 在`config`里面直接指定生成方式, 由于`lazyconfig`的特性, 会在程序运行时再生成model。
- `optim`: 和优化器相关, 在`config`里面直接指定生成方式，同上。
- `lr_scheduler`: 和学习率相关, 在`config`里面直接指定生成方式，没有定义的话则会采用默认的`lr_scheduler`。
- `graph`: 和graph模式相关(oneflow特有), 在`config`里面直接指定生成方式，同上。

基于以上的了解, 我们先来看看一个完整的`config.py`, 应该是什么样子, 

> 注意, 所有import的模块必须以libai的根目录为路径，否则保存的`yaml`文件将无法保存模块的正确路径，导致读取`yaml`报错从而不能复现实验

```python
from omegaconf import OmegaConf
from configs.common.data.bert_dataset import tokenization
from configs.common.models.bert import cfg as my_cfg
from configs.common.models.graph import graph
from configs.common.optim import optim
from configs.common.train import train
from libai.config import LazyCall
from libai.data.build import build_nlp_test_loader, build_nlp_train_loader
from libai.tokenizer import BertTokenizer
from libai.optim import get_default_optimizer_params, PolynomialLR
from projects.MyProjects.dataset.dataset import TrainDataset, TestDataset
from projects.MyProjects.modeling import MyModel


tokenization.tokenizer = LazyCall(BertTokenizer)(
    vocab_file=".../vocab.txt",
)

dataloader = OmegaConf.create()
dataloader.train = LazyCall(build_nlp_train_loader)(
    dataset=[
        LazyCall(TrainDataset)(
            path=".../train.txt",
            tokenizer=LazyCall(BertTokenizer)(
                vocab_file=".../vocab.txt"
            ),
        )
    ],
)

dataloader.test = [
    LazyCall(build_nlp_test_loader)(
        dataset=LazyCall(TestDataset)(
            path=".../test.txt",
            tokenizer=LazyCall(BertTokenizer)(
                vocab_file=".../vocab.txt"
            ),
        ),
    ),
]

my_cfg.update(
    dict(
        vocab_size=21128,
        hidden_size=768,
        hidden_layers=12,
        layernorm_eps=1e-12,
        intermediate_size=3072,
    )
)

model = LazyCall(MyModel)(cfg=my_cfg)

# 众所周知optimizer在初始化的时候, 需要model.parameters()作为入参.
# 但是model还未构建, 拿不到parameters(), 由于lazyconfig的特性, 在此处只会更新optim的以下参数, 在程序中等拿到了model.parameters()再延迟构建 
optim = LazyCall(flow.optim.AdamW)(
    parameters=LazyCall(get_default_optimizer_params)(
        # parameters.model is meant to be set to the model object, before instantiating the optimizer.
        clip_grad_max_norm=1.0,
        clip_grad_norm_type=2.0,
        weight_decay_norm=0.0,
        weight_decay_bias=0.0,
    ),
    lr=1e-4,
    weight_decay=0.01,
    betas=(0.9, 0.999),
    do_bias_correction=True,
)

lr_scheduler = LazyCall(flow.optim.lr_scheduler.WarmUpLR)(
    lrsch_or_optimizer=LazyCall(PolynomialLR)(steps=1000, end_learning_rate=1.0e-5,),
    warmup_factor=0,
    warmup_iters=100,
    warmup_method="linear",
)

train.update(
    dict(
        output_dir=".../result",
        train_micro_batch_size=64,
        test_micro_batch_size=64,
        train_epoch=1,
        train_iter=10000,
        eval_period=1000,
        dist=dict(
            data_parallel_size=1,
            tensor_parallel_size=1,
            pipeline_parallel_size=1,
        ),
    )
)

```

构建好`config.py`以后, 我们在程序中想拿到对应的字段, 只需要进行类似的访问`cfg.train.output_dir`即可.

### 开启训练

等上述的模块重载完以后, 我们就可以开启训练任务了.
`bash projects/my_projects/train.sh projects/my_projects/config.py 1`

> CONFIG可以同时支持py文件和生成的yaml文件
```bash
#!/usr/bin/env bash

CONFIG=projects/your_task/config.py #output/your_task/config.yaml
GPUS=1
NODE=1
NODE_RANK=0
PORT=2345

python3 -m oneflow.distributed.launch \
    --nproc_per_node $GPUS \
    --nnodes $NODE \
    --node_rank $NODE_RANK \
    --master_addr $PORT \
    projects/your_task/finetune.py \
    --config-file $CONFIG \
    --num-gpus $GPUS
```

**Comment by xiezipeng-ML** [comment]
这个是根据程鹏的[教程](https://github.com/Oneflow-Inc/OneTeam/issues/925)补充与修改，大家先一起看一下。

**Comment by ZylOo0** [comment]
> data: 和dataloader相关的入参，字典形式。

这个字段应该是 dataloader 吧？代码里没看到 data。

**Comment by xiezipeng-ML** [comment]
> > data: 和dataloader相关的入参，字典形式。
> 
> 这个字段应该是 dataloader 吧？代码里没看到 data。

哦哦，这个data应该是之前版本的，我删一下

**Comment by CPFLAME** [comment]
> 重新定义datasets

这里我觉得要交代一下,   datasets 里面 `__getitem__` 的返回的key, 必须和`model.forward`的入参一一匹配

**Comment by L1aoXingyu** [comment]
我们这周重点工作就是一起写 tutorial，把用户体验优化上去
