### ISSUE TITLE
libai 的个人用户体验

### ISSUE THREAD

**Issue by ZylOo0** [Oneflow-Inc/libai#170]
记录一些我在使用 libai 时遇到的问题。

**Comment by ZylOo0** [comment]
这个类实现的是 Transformer 的 Positional Encoding。我对参数有些疑惑，也许 num_embeddings 应该是 max_len？

```
class SinePositionalEmbedding(nn.Module):
    """Construct the sinusoidal positional embeddings.

    Arguments:
        num_embeddings: size of vocabulary.
        embedding_dim: dimension of embeddings.
    """
```

附上 PyTorch 的实现代码：

```
class PositionalEncoding(nn.Module):
    def __init__(self, emb_size, dropout, maxlen=5000):
        super(PositionalEncoding, self).__init__()
        den = torch.exp(-torch.arange(0, emb_size, 2) * math.log(10000) / emb_size)
        pos = torch.arange(0, maxlen).reshape(maxlen, 1)
        pos_embedding = torch.zeros((maxlen, emb_size))
        pos_embedding[:, 0::2] = torch.sin(pos * den)
        pos_embedding[:, 1::2] = torch.cos(pos * den)
        pos_embedding = pos_embedding.unsqueeze(-2)

        self.dropout = nn.Dropout(dropout)
        self.register_buffer("pos_embedding", pos_embedding)

    def forward(self, token_embedding):
        return self.dropout(
            token_embedding + self.pos_embedding[: token_embedding.size(0), :]
        )
```

**Comment by rentainhe** [comment]
> layers 里的这个类实现的是 Transformer 的 Positional Encoding。我对参数有些疑惑，也许 num_embeddings 应该是 max_len？
> 
> ```
> class SinePositionalEmbedding(nn.Module):
>     """Construct the sinusoidal positional embeddings.
> 
>     Arguments:
>         num_embeddings: size of vocabulary.
>         embedding_dim: dimension of embeddings.
>     """
> ```
> 
> 附上 PyTorch 的实现代码：
> 
> ```
> class PositionalEncoding(nn.Module):
>     def __init__(self, emb_size, dropout, maxlen=5000):
>         super(PositionalEncoding, self).__init__()
>         den = torch.exp(-torch.arange(0, emb_size, 2) * math.log(10000) / emb_size)
>         pos = torch.arange(0, maxlen).reshape(maxlen, 1)
>         pos_embedding = torch.zeros((maxlen, emb_size))
>         pos_embedding[:, 0::2] = torch.sin(pos * den)
>         pos_embedding[:, 1::2] = torch.cos(pos * den)
>         pos_embedding = pos_embedding.unsqueeze(-2)
> 
>         self.dropout = nn.Dropout(dropout)
>         self.register_buffer("pos_embedding", pos_embedding)
> 
>     def forward(self, token_embedding):
>         return self.dropout(
>             token_embedding + self.pos_embedding[: token_embedding.size(0), :]
>         )
> ```

是的，num_embeddings应该就是你输入的token的数量，对每个token加上位置embedding，然后embedding_dim应该要和token dim是一致的，这儿的命名应该在文档里有相关说明~

**Comment by L1aoXingyu** [comment]
你也可以直接提 pr 来 fix 这些问题 @ZylOo0

**Comment by doombeaker** [comment]
> num_embeddings: size of vocabulary.

我最近在push云平台同学尽快完成手头模型的 OneFlow 迁移工作，同时这个过程可能也会暴露一些 OneFlow、OneFlow 库的问题，我让他们都需要记录好，然后对接框架组的同事反馈、迭代。

不过他们基础还在打造中，如果同时负责反馈和迭代修改，可能会有些力不从心。 所以庄同学暂时不参与 libai 的代码 fix 吧。

等这波任务过了（预计2周到1个月），再过渡参与到框架组这边的工作来。
