### ISSUE TITLE
流水并行下 get_batch 中 data to_global 的修复方式讨论

### ISSUE THREAD

**Issue by Ldpe2G** [Oneflow-Inc/libai#257]
### 相关issue
https://github.com/Oneflow-Inc/libai/issues/243#issuecomment-1094166867
### 目前的修复 pr
https://github.com/Oneflow-Inc/libai/pull/255
### 相关讨论：
廖星宇:
如果他在 getitem 里面通过随机性修改 image 和 label

廖星宇:
类似 mixup 那种

廖星宇:
索引还是按我们的要求来

梁德澎:
所以直接把rank0上的发送到 rank -1是比较合理的

廖星宇:
是的，我就是想这个 pr 能不能直接把这个实现了

廖星宇:
而不是特定为 mixup 修复这个问题

廖星宇:
这样后面出错的风险也低了

梁德澎:
这个要想一下,因为分类任务

梁德澎:
有什么数据我是知道的

梁德澎:
我明确知道 label 要传

梁德澎:
所以我可以直接写死

梁德澎:
nlp类的任务，我怎么知道那些要传那些不传呢

程鹏:
![1649646192(1)](https://user-images.githubusercontent.com/2424744/162658232-6a6e230b-9ec8-4021-9dda-86be169b2c77.png)
程鹏:
这里可以加一个 prefer_placement

程鹏:
如果是None

程鹏:
就直接to_placement(placement_idx)

梁德澎:
也就是在 to_global 里处理这个问题是吧

梁德澎:
我觉得是可行的

廖星宇:
我们默认to rank0 吧

廖星宇:
或者 to stage1 的 rank

程鹏:
是的

廖星宇:
可以把 get_batch 搞得简单一点

程鹏:
但是data不一定只在 rank0上面

廖星宇:
就是数据并行的 rank

廖星宇:
因为模型并行都是 b

廖星宇:
所以可以直接发过去

廖星宇:
我们可以写一个 issue 来讨论一下

廖星宇:
如果不好实现，那可以先把这个 mixup 合了

廖星宇:
如果好实现，就在这个 pr 里面一并做了

**Comment by CPFLAME** [comment]
我比较倾向于改一下`DistTensorData`的`to_global()`代码

```python
@dataclass
class DistTensorData:
    tensor: flow.Tensor
    sbp_list: list = field(default_factory=lambda: ["split_0", "broadcast"])
    placement_idx: int = 0

    # Tensor-like methods
    def to_global(self, sbp=None, placement=None):
        if sbp is not None:
            self.sbp = sbp
        else:
            sbp_list = []
            for sbp in self.sbp_list:
                sbp = sbp.split("_")
                if len(sbp) > 1:
                    # split dim
                    assert sbp[0] == "split"
                    split_dim = int(sbp[1])
                    sbp_list.append(flow.sbp.split(split_dim))
                else:
                    sbp_sign = sbp[0]
                    sbp_list.append(getattr(flow.sbp, sbp_sign))
            self.sbp = dist.get_nd_sbp(sbp_list)

        if placement is not None:
            self.tensor = self.tensor.to_global(sbp=self.sbp, placement=placement)
        else:
            main_placement = dist.get_layer_placement(0)
            self.tensor = self.tensor.to_global(sbp=self.sbp, placement=main_placement)
            if self.placement_idx != 0:
                self.tensor = self.tensor.to_global(placement=dist.get_layer_placement(self.placement_idx))
```
这样用户直接调用这个函数就可以了, 而不用在自定义get_batch()的时候, 到代码里面去扒
