### ISSUE TITLE
Swin 模型加载 checkpoint 训练0号卡显存显著增多 

### ISSUE THREAD

**Issue by Ldpe2G** [Oneflow-Inc/libai#292]
## 现象描述

中兴那边的用户反馈，加载checkpoint继续训练的时候，发现 0 号卡显存显著增多，然后我发现用  swin 也可以复现问题，以下是实验数据：

### 配置： batch 32，graph fp16， data parallel 4
|                           | 编译 train graph 后开始训练的显存 | 第一次编译 val graph 后的显存 |
| ------------------------- | --------------------------------- | --------------------------------- |
| swin tiny 重头训          | 3610                              | 3874                              |
| swin tiny 加载checkpoint  | 4102                              | 4346                              |
| swin small 重头训         | 4936                              | 5200                              |
| swin small 加载checkpoint | 5754                              | 5998                              |
| swin base 重头训          | 6368                              | 6632                              |
| swin base 加载checkpoint  | 7816                     | 8060                    |

### 配置： batch 32，eager fp32， data parallel 4
|                           | 开始训练的显存 | 接着第一次跑 val 的显存 |
| ------------------------- | -------------- | ----------------------- |
| swin tiny 重头训          | 5814           | 5834                    |
| swin tiny 加载checkpoint  | 6278           | 6278                    |
| swin small 重头训         | 8308           | 8328                    |
| swin small 加载checkpoint | 9072           | 9072                    |
| swin base 重头训          | 11156          | 11176                   |
| swin base 加载checkpoint  | 12144  | 12144          |

### 实验结论
从数据上可以看到，不管是eager还是 graph ，对于0号卡上的显存占用，加载checkpoint继续训的方式比不加载的方式都会多不少，而且随着模型的增大，多的越多。

## 问题定位
然后通过阅读代码，实验分析，发现修改 oneflow `check_point_v2.py` 的代码为如下，则显存占用会降低很多，但是还是比不加载多一些

```bash
diff --git a/python/oneflow/framework/check_point_v2.py b/python/oneflow/framework/check_point_v2.py
index f45a074b86..db1117b366 100644
--- a/python/oneflow/framework/check_point_v2.py
+++ b/python/oneflow/framework/check_point_v2.py
@@ -132,11 +132,11 @@ def _LoadSingleVariable(
             file_backed_blob = FileBackendVariableBlob(path)
             loaded = flow.tensor(
                 file_backed_blob.numpy(), dtype=file_backed_blob.dtype
-            ).to("cuda")
+            )#.to("cuda")
         else:
-            loaded = flow.tensor([]).to("cuda")
+            loaded = flow.tensor([])#.to("cuda")
         loaded = loaded.to_global(
-            flow.placement("cuda", [global_src_rank]), flow.sbp.broadcast
+            flow.placement("cpu", [global_src_rank]), flow.sbp.broadcast
         )
         return loaded

```

### 配置： batch 32，graph fp16， data parallel 4
|                           | 编译 train graph 后开始训练的显存 | 第一次编译 val graph 后的显存 |
| ------------------------- | --------------------------------- | --------------------------------- |
| swin base 重头训          | 6368                              | 6632                              |
| swin base 加载checkpoint  | 6490                     | 6734                    |

### 配置： batch 32，eager fp32， data parallel 4
|                           | 开始训练的显存 | 接着第一次跑 val 的显存 |
| ------------------------- | -------------- | ----------------------- |
| swin base 重头训          | 11156          | 11176                   |
| swin base 加载checkpoint  | 11292  | 11292         |

**Comment by leaves-zwx** [comment]
那就是验证了那个测试，flow.load 把 tensor 加载到显存里面去了。根据当时的设计，这些 tensor 应该在cpu内存上。

**Comment by daquexian** [comment]
> 那就是验证了那个猜测，flow.load 把 tensor 加载到显存里面去了。根据当时的设计，这些 tensor 应该在cpu内存上。

+1，这里最开始好像是 cpu 的 boxing 功能不完整所以就把 tensor 加载到 cuda 上了，后来一直没修改

在 module.load_state_dict 时会有一次 boxing（把 load 得到的 tensor boxing 成和 parameter 相同的 placement 和 sbp），如果 load 得到 cpu tensor，那会有一个 cpu 0 -> gpu 0-3 的 boxing，不知道这个 boxing 过程中会不会在 gpu 0 上生成较大的中间 tensor

**Comment by clackhan** [comment]
> 如果 load 得到 cpu tensor，那 boxing 就是 cpu 0 -> gpu 0-3，不知道这个 boxing 过程中会不会在 gpu 0 上生成较大的中间 tensor

可以先打开ONEFLOW_DEBUG_MODE，在日志里看看加载过程都发生了哪些 eager boxing

**Comment by Ldpe2G** [comment]
> > 如果 load 得到 cpu tensor，那 boxing 就是 cpu 0 -> gpu 0-3，不知道这个 boxing 过程中会不会在 gpu 0 上生成较大的中间 tensor
> 
> 可以先打开ONEFLOW_DEBUG_MODE，在日志里看看加载过程都发生了哪些 eager boxing

swin 模型加载过程中都是下面这个boxing

```bash
Altered state of sbp: (B) -> (B) -> (B) -> (B) -> (B)
Altered state of placement: oneflow.placement(type="cpu", ranks=[0]) -> oneflow.placement(type="cuda", ranks=[0]) -> oneflow.placement(type="cuda", ranks=[0]) -> oneflow.placement(type="cuda", ranks=[0, 1, 2, 3]) -> oneflow.placement(type="cuda", ranks=[0, 1, 2, 3])
Boxing route: copy-h2d -> identity -> asymmetric-broadcast -> identity

```

**Comment by strint** [comment]
> oneflow.placement(type="cpu", ranks=[0]) -> oneflow.placement(type="cuda", ranks=[0])

这个是 flow.load 时的 boxing 对吧？

如果是的，那么这个是不正常的，flow.load 时，模型被加载到 gpu，那么模型会以 B 存在显存中；加上 nn.Module 中的一份，就翻倍了。

**Comment by Ldpe2G** [comment]
> > oneflow.placement(type="cpu", ranks=[0]) -> oneflow.placement(type="cuda", ranks=[0])
> 
> 这个是 flow.load 时的 boxing 对吧？
> 
> 如果是的，那么这个是不正常的，flow.load 时，模型被加载到 gpu，那么模型会以 B 存在显存中；加上 nn.Module 中的一份，显存就翻倍了。

这是上面修改 `check_point_v2.py` 之后的boxing，但是0号卡显存占用确实比修改前少了很多

**Comment by daquexian** [comment]
这个应该是 load_state_dict 时的 boxing
```python
tmp = flow.load(path)
module.load_state_dict(tmp)
```
load_state_dict 里会遍历 tmp 里的 tensor，对每一个 tensor 先 boxing 再 copy 到 parameter，boxing 得到的 tensor copy 完就会析构，所以显存不会翻倍。不过那个临时变量仍然会引起额外的显存占用。要完全解决这个问题应该要支持用 cpu tensor 来 assign 一个 gpu tensor

**Comment by leaves-zwx** [comment]
tmp 里的 tensor 占用的显存什么时候会释放呢？

**Comment by daquexian** [comment]
> tmp 里的 tensor 占用的显存什么时候会释放呢？

depeng 修改过之后 tmp 就在 cpu 上了。在修改之前，因为一般写法是 `module.load_state_dict(flow.load(path))`，所以一般也是用完之后就被 python 解释器析构了

**Comment by clackhan** [comment]
是不是可以手动干涉eager boxing路径，使之不产生cuda类型中间tensor，比如对于 ```weight (placement("cuda", [0, 1, 2, 3]))```，对于加载进来的```cpu_weight(placement("cpu", [0]))```，现转换为```weight_tmp (placement("cpu", [0, 1, 2, 3])) # 
 placement_tmp = replace_device_type_with_cpu(weigth's placement)```，再转到cuda上

**Comment by clackhan** [comment]
> > tmp 里的 tensor 占用的显存什么时候会释放呢？
> 
> depeng 修改过之后 tmp 就在 cpu 上了。在修改之前，因为一般写法是 `module.load_state_dict(flow.load(path))`，所以一般也是用完之后就被 python 解释器析构了

cuda 类型的tensor 即使释放了，其申请的显存也不会释放，因为cuda allocator 采用的是内存池机制

**Comment by daquexian** [comment]
> 是不是可以手动干涉eager boxing路径，使之不产生cuda类型中间tensor

我后来想了想这个中间 tensor 只有在模型 sbp 为 s 的时候才会有额外的显存占用，sbp 为 b 的时候即使先做 cpu 的 broadcast，下一步也是需要再 to 到 cuda 并占一份显存的，支持直接用 cpu tensor assign gpu tensor 才能省掉这份显存

**Comment by clackhan** [comment]
> sbp 为 b 的时候即使先做 cpu 的 broadcast，下一步也是需要再 to 到 cuda 并占一份显存的

看德鹏的日志应该 sbp 为 b 的时候是先做的 copy h to d，然后做 cuda 的 broadcast，所以还是多占了几分显存

```
Altered state of sbp: (B) -> (B) -> (B) -> (B) -> (B)
Altered state of placement: oneflow.placement(type="cpu", ranks=[0]) -> oneflow.placement(type="cuda", ranks=[0]) -> oneflow.placement(type="cuda", ranks=[0]) -> oneflow.placement(type="cuda", ranks=[0, 1, 2, 3]) -> oneflow.placement(type="cuda", ranks=[0, 1, 2, 3])
Boxing route: copy-h2d -> identity -> asymmetric-broadcast -> identity

```

**Comment by clackhan** [comment]
> 下一步也是需要再 to 到 cuda 并占一份显存的，支持直接用 cpu tensor assign gpu tensor 才能省掉这份显存

 to 到 cuda之后的tensor直接赋值给paremeter 不可以吗，这个样是不是就没有多占显存？

**Comment by clackhan** [comment]
> 支持直接用 cpu tensor assign gpu tensor 才能省掉这份显存

明白了，Parameter没有延迟初始化机制，所以还是要支持直接用cpu tensor assign gpu tensor 才能work

**Comment by daquexian** [comment]
https://github.com/Oneflow-Inc/oneflow/compare/fix_extra_memory_in_load

hotfix 了一下，@Ldpe2G 可以试一下这个分支 @clackhan

**Comment by Ldpe2G** [comment]
> https://github.com/Oneflow-Inc/oneflow/compare/fix_extra_memory_in_load
> 
> hotfix 了一下，@Ldpe2G 可以试一下这个分支 @clackhan

试验了一下，这样改了之后：

swin base, eager fp32 0号卡显存占用，看起来差不多了

不加载checkpoint: 11131 M
加载 checkpoint  :  11117 M

**Comment by daquexian** [comment]
好的。显存反而小了吗😂 那我吃完饭整理一下提一个 pr

**Comment by Ldpe2G** [comment]
> 好的。显存反而小了吗😂 那我吃完饭整理一下提一个 pr

看起来是的 😄

**Comment by Ldpe2G** [comment]
基于修复之后的 master 重新测了一下0号卡显存占用，跑了5次取平均

swin base eager fp32 batch=4 data_parallel=4

加载checkpoint：    4137M
不加载checkpoint:   4082M

平均多~50M，和昨天的数据有些出入

**Comment by daquexian** [comment]
> 基于修复之后的 master 重新测了一下0号卡显存占用，跑了5次取平均
> 
> swin base eager fp32 batch=4 data_parallel=4
> 
> 加载checkpoint： 4137M 不加载checkpoint: 4082M
> 
> 加载checkpoint训的话还是比不加载平均多~50M，和昨天的数据有些出入

😂 令人费解，@clackhan binbin 有什么想法吗，那个 pr 应该已经消除了 load 过程中的额外显存？

**Comment by clackhan** [comment]
能先打开ONEFLOW_DEBUG_MODE（打开DEBUG的时候顺便再看看显存情况），看看eager boxing日志吗？ 还有这个仅在0号卡上多了50M吗，

**Comment by Ldpe2G** [comment]
## swin base， batch 2， data_parallel 2， eager fp32，5次取平均

|                   | gpu 0    |  gpu 1    |
| ----------------- | ---- | ---- |
| load checkpoint   | 3360 | 3279 |
| 不load checkpoint | 3254 | 3277 |

ONEFLOW_DEBUG_MODE 打开的Log: 
[log.tar.gz](https://github.com/Oneflow-Inc/libai/files/8776238/log.tar.gz)

**Comment by clackhan** [comment]
> ## swin base， batch 2， data_parallel 2， eager fp32，5次取平均
> gpu 0	gpu 1
> load checkpoint	3360	3279
> 不load checkpoint	3254	3277
> ONEFLOW_DEBUG_MODE 打开的Log: [log.tar.gz](https://github.com/Oneflow-Inc/libai/files/8776238/log.tar.gz)

@Ldpe2G 能上传一下没有oad checkpoint 的日志吗？

**Comment by Ldpe2G** [comment]
加载和不加载checkpoint都重新弄了一份，之前的Log只记录到加载checkpoint之后就停了
[load_checkpoint_log.tar.gz](https://github.com/Oneflow-Inc/libai/files/8776453/load_checkpoint_log.tar.gz)
[not_load_checkpoint_log.tar.gz](https://github.com/Oneflow-Inc/libai/files/8776454/not_load_checkpoint_log.tar.gz)

**Comment by clackhan** [comment]
看日志，发现加载模型部分有两种 eager boxing，第一种符合预期，第二种有出现了copy h2d，应该是这个导致了显存的占用
```bash
# 第一种
I20220526 04:58:44.751351 880386 eager_boxing_logger.cpp:42] Boxing route: identity -> asymmetric-broadcast
I20220526 04:58:44.751379 880386 eager_boxing_logger.cpp:43] Logical shape: (100,)
I20220526 04:58:44.751390 880386 eager_boxing_logger.cpp:44] Altered state of sbp: (B) -> (B) -> (B)
I20220526 04:58:44.751399 880386 eager_boxing_logger.cpp:45] Altered state of placement: oneflow.placement(type="cpu", ranks=[0]) -> oneflow.placement(type="cpu", ranks=[0]) -> oneflow.placement(type="cpu", ranks=[0, 1])

# 第二种
I20220526 04:58:44.757539 880386 eager_boxing_logger.cpp:42] Boxing route: copy-h2d -> identity -> asymmetric-broadcast -> identity
I20220526 04:58:44.757567 880386 eager_boxing_logger.cpp:43] Logical shape: (128,3,4,4)
I20220526 04:58:44.757577 880386 eager_boxing_logger.cpp:44] Altered state of sbp: (B) -> (B) -> (B) -> (B) -> (B)
I20220526 04:58:44.757598 880386 eager_boxing_logger.cpp:45] Altered state of placement: oneflow.placement(type="cpu", ranks=[0]) -> oneflow.placement(type="cuda", ranks=[0]) -> oneflow.placement(type="cuda", ranks=[0]) -> oneflow.placement(type="cuda", ranks=[0, 1]) -> oneflow.placement(type="cuda", ranks=[0, 1])
```

**Comment by clackhan** [comment]
> 加载和不加载checkpoint都重新弄了一份，之前的Log只记录到加载checkpoint之后就停了 [load_checkpoint_log.tar.gz](https://github.com/Oneflow-Inc/libai/files/8776453/load_checkpoint_log.tar.gz) [not_load_checkpoint_log.tar.gz](https://github.com/Oneflow-Inc/libai/files/8776454/not_load_checkpoint_log.tar.gz)

@Ldpe2G 这个我如何能够复现呢？或则我们联调一下？

**Comment by Ldpe2G** [comment]
> 基于修复之后的 master 重新测了一下0号卡显存占用，跑了5次取平均
> 
> swin base eager fp32 batch=4 data_parallel=4
> 
> 加载checkpoint： 4137M 不加载checkpoint: 4082M
> 
> 加载checkpoint训的话还是比不加载平均多~50M，和昨天的数据有些出入

问题已经定位并修复： https://github.com/Oneflow-Inc/oneflow/pull/8310
