### ISSUE TITLE
想问问现在有转换hugging face模型的代码了吗？

### ISSUE THREAD

**Issue by drxmy** [Oneflow-Inc/libai#310]
不是催更，在issue和pr里逛了一圈，感觉好像快有了？如果快要更新了，就不自己折腾了。是想试试T5的3D并行。

顺便问一下，T5是支持pipeline并行吗？我看megatron代码里写的有decoder的情况下没有pipeline。

**Comment by strint** [comment]
@CPFLAME

**Comment by CPFLAME** [comment]
> 顺便问一下，T5是支持pipeline并行吗

T5是支持pipeline并行的, 3D并行也支持, 可以根据libaid的doc说明来尝试https://libai.readthedocs.io/en/latest/tutorials/basics/Distributed_Configuration.html

> 转换hugging face的代码

目前 有bert相关的转换代码, https://libai.readthedocs.io/en/latest/notes/How_to_use_huggingface%27s_weights_in_LiBai.html#, 
但是每个model中的key都是独一无二的, 所以其他的model需要额外在写一些转换脚本, 其他的转换代码 @xiezipeng-ML 比较熟悉目前的状况

**Comment by drxmy** [comment]
知道了，我先研究一下，谢谢各位

**Comment by xiezipeng-ML** [comment]
> 知道了，我先研究一下，谢谢各位

你好，使用中遇到问题的话可以联系我
