### ISSUE TITLE
微信群满了

### ISSUE THREAD

**Issue by MissiontoMars** [Oneflow-Inc/libai#433]
如题

**Comment by xiezipeng-ML** [comment]
您好，可以加这个
![579aa55f4499d4aa40500420d7264f3](https://user-images.githubusercontent.com/53039617/203809530-f228d03b-a333-4e3f-a8cf-cc15a8737a40.png)

**Comment by MetaBlues** [comment]
@xiezipeng-ML 二维码过期了，求一个新的加群方式

**Comment by xiezipeng-ML** [comment]
@MetaBlues 你好，可以先用这个，之后我们提供永久二维码
![dfa4208e9019dd90755fc21b04715fc](https://user-images.githubusercontent.com/53039617/205544878-edeb2398-6935-4df0-bbb0-f5dee5b8fb15.png)

**Comment by vicwer** [comment]
> @MetaBlues 你好，可以先用这个，之后我们提供永久二维码 ![dfa4208e9019dd90755fc21b04715fc](https://user-images.githubusercontent.com/53039617/205544878-edeb2398-6935-4df0-bbb0-f5dee5b8fb15.png)

您好，请问可以发个可以进群的二维码吗

**Comment by vicwer** [comment]
@xiezipeng-ML 您好，请问可以发个可以进群的二维码吗，上图的二维码过期了

**Comment by xiezipeng-ML** [comment]
libai的github首页最底部是永久二维码：https://github.com/Oneflow-Inc/libai
