### ISSUE TITLE
[多机多卡][MT5]failed to connect to all addresses

### ISSUE THREAD

**Issue by MikeDean2367** [Oneflow-Inc/libai#470]
![1](https://user-images.githubusercontent.com/65744560/223310913-df61dda6-80df-4ad9-9ec0-99ede8fad426.png)
如上图所示，运行的命令分别为：
`CUDA_VISIBLE_DEVICES=1,5 NODE=2 NODE_RANK=0 ADDR=10.82.1.210 PORT=12345 bash tools/train.sh projects/MT5/train_net.py projects/MT5/configs/mt5_pretrain.py 2` 
`NODE=2 NODE_RANK=1 ADDR=10.82.1.210 PORT=12345 bash tools/train.sh projects/MT5/train_net.py projects/MT5/configs/mt5_pretrain.py 2`
两台机器可以免密ssh，且端口12345开放，使用`nc -l 12345` `nc MASTER_IP 12345`，测试端口正常开放。
但是一直无法建立连接。
咨询了libai的团队，我把防火墙关闭后即可正常执行多机多卡运行。

**Comment by shangguanshiyuan** [comment]
你好，oneflow在分布式环境下使用英伟达的gpu进行计算，通常情况下涉及三部分的通信，分别是oneflow实现的数据传输平面的通信、oneflow中使用rpc进行控制平面的通信、以及计算设备厂商提供的通信库如nccl。
在您的报错信息中，就是控制平面的rpc连接失败。
目前，rpc的连接和数据传输使用的端口是自动搜索的，所以目前需要您通过关闭防火墙以使得网络可以正常建立。
之后我们也会提供相关接口，用于配置数据传输平面和控制平面使用指定端口。
感谢您的反馈。
